export const sitesData = [
  {
    id: '6a1c146c',
    sitesBasic: {
      settings: {
        locationName: "Map",
        radius: "300m",
        coordinates: "31.8952020 / 34.9818310",
        location: "Active/Not Active/Mix",
        locationDate: "20.01.2024",
      },
      summary: {
        manager: "Moti Rush",
        atSite: "32",
        present: "26",
        absent: "6 , 2 more than 3 Days",
      },
      schedule: {
        firstShift: {
          "1-5": "06:30-18:00",
          6: "06:00-12:00",
          transportation: "1 Hour",
          break: "12:00-13:00",
        },
        secondShift: {
          "1-5": "06:30-18:30",
          6: "06:00-12:00",
        },
      },
    },
    sitesWorkedTime: [
      {
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Yar",
        workedTime: {
          brutto: "221:16",
          netto: "205:04",
        },
        manager: "Kobi Kats",
        days: "22",
        site: "Ramat Aviv",
      },
      {
        name: "Ion Sinu",
        photo: "https://frontwebil.github.io/RIGO-photos/img/man-yellow.svg",
        customer: "Yar",
        workedTime: {
          brutto: "262:05",
          netto: "225:49",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Ramat Aviv",
      },
      {
        name: "Victor Jacota",
        photo: "https://frontwebil.github.io/RIGO-photos/img/black-man.svg",
        customer: "Extra",
        workedTime: {
          brutto: "161:36",
          netto: "128:08",
        },
        manager: "Moti Rush",
        days: "16",
        site: "Ramat Aviv",
      },
      {
        name: "Mihal Clmentov",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Inta",
        workedTime: {
          brutto: "242:52",
          netto: "227:05",
        },
        manager: "Moti Rush",
        days: "22",
        site: "Ramat Aviv",
      },
      {
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/angry-man.svg",
        customer: "Inta",
        workedTime: {
          brutto: "221:16",
          netto: "105:04",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Ramat Aviv",
      },
    ],
    sitesActions: [
      {
        date: {
          day: "12",
          month: "04",
          year: "2024",
          time: "07:19",
        },
        location: {
          type: "Enter",
          distance: "At Site",
        },
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Yar",
        workedTime: {
          brutto: "00:00",
          netto: "00:00",
        },
        manager: "Kobi Kats",
        days: "22",
        site: "Adassa",
      },
      {
        date: {
          day: "11",
          month: "04",
          year: "2024",
          time: "10:46",
        },
        location: {
          type: "Exit",
          distance: "900m",
        },
        name: "Ion Sinu",
        photo: "https://frontwebil.github.io/RIGO-photos/img/man-yellow.svg",
        customer: "Yar",
        workedTime: {
          brutto: "10:02",
          netto: "10:26",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Adassa",
      },
      {
        date: {
          day: "08",
          month: "04",
          year: "2024",
          time: "12:20",
        },
        location: {
          type: "Brake",
          distance: "At Site",
        },
        name: "Victor Jacota",
        photo: "https://frontwebil.github.io/RIGO-photos/img/black-man.svg",
        customer: "Extra",
        workedTime: {
          brutto: "04:20",
          netto: "04:00",
        },
        manager: "Moti Rush",
        days: "16",
        site: "Adassa",
      },
      {
        date: {
          day: "06",
          month: "04",
          year: "2024",
          time: "07:52",
        },
        location: {
          type: "Colleague",
          distance: "At Site",
        },
        name: "Mihal Clmentov",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Inta",
        workedTime: {
          brutto: "00:00",
          netto: "00:00",
        },
        manager: "Moti Rush",
        days: "22",
        site: "Adassa",
      },
      {
        date: {
          day: "11",
          month: "04",
          year: "2024",
          time: "18:46",
        },
        location: {
          type: "Exit",
          distance: "At Site",
        },
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/angry-man.svg",
        customer: "Inta",
        workedTime: {
          brutto: "01:01",
          netto: "10:26",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Adassa",
      },
    ],
  },
  {
    id: "0fa08a70",
    sitesBasic: {
      settings: {
        locationName: "Map",
        radius: "300m",
        coordinates: "31.8952020 / 34.9818310",
        location: "Active/Not Active/Mix",
        locationDate: "20.01.2024",
      },
      summary: {
        manager: "Moti Rush",
        atSite: "32",
        present: "26",
        absent: "6 , 2 more than 3 Days",
      },
      schedule: {
        firstShift: {
          "1-5": "06:30-18:00",
          6: "06:00-12:00",
          transportation: "1 Hour",
          break: "12:00-13:00",
        },
        secondShift: {
          "1-5": "06:30-18:30",
          6: "06:00-12:00",
        },
      },
    },
    sitesWorkedTime: [
      {
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Yar",
        workedTime: {
          brutto: "221:16",
          netto: "205:04",
        },
        manager: "Kobi Kats",
        days: "22",
        site: "Ramat Aviv",
      },
      {
        name: "Ion Sinu",
        photo: "https://frontwebil.github.io/RIGO-photos/img/man-yellow.svg",
        customer: "Yar",
        workedTime: {
          brutto: "262:05",
          netto: "225:49",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Ramat Aviv",
      },
      {
        name: "Victor Jacota",
        photo: "https://frontwebil.github.io/RIGO-photos/img/black-man.svg",
        customer: "Extra",
        workedTime: {
          brutto: "161:36",
          netto: "128:08",
        },
        manager: "Moti Rush",
        days: "16",
        site: "Ramat Aviv",
      },
      {
        name: "Mihal Clmentov",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Inta",
        workedTime: {
          brutto: "242:52",
          netto: "227:05",
        },
        manager: "Moti Rush",
        days: "22",
        site: "Ramat Aviv",
      },
      {
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/angry-man.svg",
        customer: "Inta",
        workedTime: {
          brutto: "221:16",
          netto: "105:04",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Ramat Aviv",
      },
    ],
    sitesActions: [
      {
        date: {
          day: "12",
          month: "04",
          year: "2024",
          time: "07:19",
        },
        location: {
          type: "Enter",
          distance: "At Site",
        },
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Yar",
        workedTime: {
          brutto: "00:00",
          netto: "00:00",
        },
        manager: "Kobi Kats",
        days: "22",
        site: "Adassa",
      },
      {
        date: {
          day: "11",
          month: "04",
          year: "2024",
          time: "10:46",
        },
        location: {
          type: "Exit",
          distance: "900m",
        },
        name: "Ion Sinu",
        photo: "https://frontwebil.github.io/RIGO-photos/img/man-yellow.svg",
        customer: "Yar",
        workedTime: {
          brutto: "10:02",
          netto: "10:26",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Adassa",
      },
      {
        date: {
          day: "08",
          month: "04",
          year: "2024",
          time: "12:20",
        },
        location: {
          type: "Brake",
          distance: "At Site",
        },
        name: "Victor Jacota",
        photo: "https://frontwebil.github.io/RIGO-photos/img/black-man.svg",
        customer: "Extra",
        workedTime: {
          brutto: "04:20",
          netto: "04:00",
        },
        manager: "Moti Rush",
        days: "16",
        site: "Adassa",
      },
      {
        date: {
          day: "06",
          month: "04",
          year: "2024",
          time: "07:52",
        },
        location: {
          type: "Colleague",
          distance: "At Site",
        },
        name: "Mihal Clmentov",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Inta",
        workedTime: {
          brutto: "00:00",
          netto: "00:00",
        },
        manager: "Moti Rush",
        days: "22",
        site: "Adassa",
      },
      {
        date: {
          day: "11",
          month: "04",
          year: "2024",
          time: "18:46",
        },
        location: {
          type: "Exit",
          distance: "At Site",
        },
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/angry-man.svg",
        customer: "Inta",
        workedTime: {
          brutto: "01:01",
          netto: "10:26",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Adassa",
      },
    ],
  },
  {
    id: "dae94f70",
    sitesBasic: {
      settings: {
        locationName: "Map",
        radius: "300m",
        coordinates: "31.8952020 / 34.9818310",
        location: "Active/Not Active/Mix",
        locationDate: "20.01.2024",
      },
      summary: {
        manager: "Moti Rush",
        atSite: "32",
        present: "26",
        absent: "6 , 2 more than 3 Days",
      },
      schedule: {
        firstShift: {
          "1-5": "06:30-18:00",
          6: "06:00-12:00",
          transportation: "1 Hour",
          break: "12:00-13:00",
        },
        secondShift: {
          "1-5": "06:30-18:30",
          6: "06:00-12:00",
        },
      },
    },
    sitesWorkedTime: [
      {
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Yar",
        workedTime: {
          brutto: "221:16",
          netto: "205:04",
        },
        manager: "Kobi Kats",
        days: "22",
        site: "Ramat Aviv",
      },
      {
        name: "Ion Sinu",
        photo: "https://frontwebil.github.io/RIGO-photos/img/man-yellow.svg",
        customer: "Yar",
        workedTime: {
          brutto: "262:05",
          netto: "225:49",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Ramat Aviv",
      },
      {
        name: "Victor Jacota",
        photo: "https://frontwebil.github.io/RIGO-photos/img/black-man.svg",
        customer: "Extra",
        workedTime: {
          brutto: "161:36",
          netto: "128:08",
        },
        manager: "Moti Rush",
        days: "16",
        site: "Ramat Aviv",
      },
      {
        name: "Mihal Clmentov",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Inta",
        workedTime: {
          brutto: "242:52",
          netto: "227:05",
        },
        manager: "Moti Rush",
        days: "22",
        site: "Ramat Aviv",
      },
      {
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/angry-man.svg",
        customer: "Inta",
        workedTime: {
          brutto: "221:16",
          netto: "105:04",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Ramat Aviv",
      },
    ],
    sitesActions: [
      {
        date: {
          day: "12",
          month: "04",
          year: "2024",
          time: "07:19",
        },
        location: {
          type: "Enter",
          distance: "At Site",
        },
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Yar",
        workedTime: {
          brutto: "00:00",
          netto: "00:00",
        },
        manager: "Kobi Kats",
        days: "22",
        site: "Adassa",
      },
      {
        date: {
          day: "11",
          month: "04",
          year: "2024",
          time: "10:46",
        },
        location: {
          type: "Exit",
          distance: "900m",
        },
        name: "Ion Sinu",
        photo: "https://frontwebil.github.io/RIGO-photos/img/man-yellow.svg",
        customer: "Yar",
        workedTime: {
          brutto: "10:02",
          netto: "10:26",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Adassa",
      },
      {
        date: {
          day: "08",
          month: "04",
          year: "2024",
          time: "12:20",
        },
        location: {
          type: "Brake",
          distance: "At Site",
        },
        name: "Victor Jacota",
        photo: "https://frontwebil.github.io/RIGO-photos/img/black-man.svg",
        customer: "Extra",
        workedTime: {
          brutto: "04:20",
          netto: "04:00",
        },
        manager: "Moti Rush",
        days: "16",
        site: "Adassa",
      },
      {
        date: {
          day: "06",
          month: "04",
          year: "2024",
          time: "07:52",
        },
        location: {
          type: "Colleague",
          distance: "At Site",
        },
        name: "Mihal Clmentov",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Inta",
        workedTime: {
          brutto: "00:00",
          netto: "00:00",
        },
        manager: "Moti Rush",
        days: "22",
        site: "Adassa",
      },
      {
        date: {
          day: "11",
          month: "04",
          year: "2024",
          time: "18:46",
        },
        location: {
          type: "Exit",
          distance: "At Site",
        },
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/angry-man.svg",
        customer: "Inta",
        workedTime: {
          brutto: "01:01",
          netto: "10:26",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Adassa",
      },
    ],
  },
  {
    id: "210ae93e",
    sitesBasic: {
      settings: {
        locationName: "Map",
        radius: "300m",
        coordinates: "31.8952020 / 34.9818310",
        location: "Active/Not Active/Mix",
        locationDate: "20.01.2024",
      },
      summary: {
        manager: "Moti Rush",
        atSite: "32",
        present: "26",
        absent: "6 , 2 more than 3 Days",
      },
      schedule: {
        firstShift: {
          "1-5": "06:30-18:00",
          6: "06:00-12:00",
          transportation: "1 Hour",
          break: "12:00-13:00",
        },
        secondShift: {
          "1-5": "06:30-18:30",
          6: "06:00-12:00",
        },
      },
    },
    sitesWorkedTime: [
      {
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Yar",
        workedTime: {
          brutto: "221:16",
          netto: "205:04",
        },
        manager: "Kobi Kats",
        days: "22",
        site: "Ramat Aviv",
      },
      {
        name: "Ion Sinu",
        photo: "https://frontwebil.github.io/RIGO-photos/img/man-yellow.svg",
        customer: "Yar",
        workedTime: {
          brutto: "262:05",
          netto: "225:49",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Ramat Aviv",
      },
      {
        name: "Victor Jacota",
        photo: "https://frontwebil.github.io/RIGO-photos/img/black-man.svg",
        customer: "Extra",
        workedTime: {
          brutto: "161:36",
          netto: "128:08",
        },
        manager: "Moti Rush",
        days: "16",
        site: "Ramat Aviv",
      },
      {
        name: "Mihal Clmentov",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Inta",
        workedTime: {
          brutto: "242:52",
          netto: "227:05",
        },
        manager: "Moti Rush",
        days: "22",
        site: "Ramat Aviv",
      },
      {
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/angry-man.svg",
        customer: "Inta",
        workedTime: {
          brutto: "221:16",
          netto: "105:04",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Ramat Aviv",
      },
    ],
    sitesActions: [
      {
        date: {
          day: "12",
          month: "04",
          year: "2024",
          time: "07:19",
        },
        location: {
          type: "Enter",
          distance: "At Site",
        },
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Yar",
        workedTime: {
          brutto: "00:00",
          netto: "00:00",
        },
        manager: "Kobi Kats",
        days: "22",
        site: "Adassa",
      },
      {
        date: {
          day: "11",
          month: "04",
          year: "2024",
          time: "10:46",
        },
        location: {
          type: "Exit",
          distance: "900m",
        },
        name: "Ion Sinu",
        photo: "https://frontwebil.github.io/RIGO-photos/img/man-yellow.svg",
        customer: "Yar",
        workedTime: {
          brutto: "10:02",
          netto: "10:26",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Adassa",
      },
      {
        date: {
          day: "08",
          month: "04",
          year: "2024",
          time: "12:20",
        },
        location: {
          type: "Brake",
          distance: "At Site",
        },
        name: "Victor Jacota",
        photo: "https://frontwebil.github.io/RIGO-photos/img/black-man.svg",
        customer: "Extra",
        workedTime: {
          brutto: "04:20",
          netto: "04:00",
        },
        manager: "Moti Rush",
        days: "16",
        site: "Adassa",
      },
      {
        date: {
          day: "06",
          month: "04",
          year: "2024",
          time: "07:52",
        },
        location: {
          type: "Colleague",
          distance: "At Site",
        },
        name: "Mihal Clmentov",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Inta",
        workedTime: {
          brutto: "00:00",
          netto: "00:00",
        },
        manager: "Moti Rush",
        days: "22",
        site: "Adassa",
      },
      {
        date: {
          day: "11",
          month: "04",
          year: "2024",
          time: "18:46",
        },
        location: {
          type: "Exit",
          distance: "At Site",
        },
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/angry-man.svg",
        customer: "Inta",
        workedTime: {
          brutto: "01:01",
          netto: "10:26",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Adassa",
      },
    ],
  },
  {
    id: "da73abdf",
    sitesBasic: {
      settings: {
        locationName: "Map",
        radius: "300m",
        coordinates: "31.8952020 / 34.9818310",
        location: "Active/Not Active/Mix",
        locationDate: "20.01.2024",
      },
      summary: {
        manager: "Moti Rush",
        atSite: "32",
        present: "26",
        absent: "6 , 2 more than 3 Days",
      },
      schedule: {
        firstShift: {
          "1-5": "06:30-18:00",
          6: "06:00-12:00",
          transportation: "1 Hour",
          break: "12:00-13:00",
        },
        secondShift: {
          "1-5": "06:30-18:30",
          6: "06:00-12:00",
        },
      },
    },
    sitesWorkedTime: [
      {
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Yar",
        workedTime: {
          brutto: "221:16",
          netto: "205:04",
        },
        manager: "Kobi Kats",
        days: "22",
        site: "Ramat Aviv",
      },
      {
        name: "Ion Sinu",
        photo: "https://frontwebil.github.io/RIGO-photos/img/man-yellow.svg",
        customer: "Yar",
        workedTime: {
          brutto: "262:05",
          netto: "225:49",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Ramat Aviv",
      },
      {
        name: "Victor Jacota",
        photo: "https://frontwebil.github.io/RIGO-photos/img/black-man.svg",
        customer: "Extra",
        workedTime: {
          brutto: "161:36",
          netto: "128:08",
        },
        manager: "Moti Rush",
        days: "16",
        site: "Ramat Aviv",
      },
      {
        name: "Mihal Clmentov",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Inta",
        workedTime: {
          brutto: "242:52",
          netto: "227:05",
        },
        manager: "Moti Rush",
        days: "22",
        site: "Ramat Aviv",
      },
      {
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/angry-man.svg",
        customer: "Inta",
        workedTime: {
          brutto: "221:16",
          netto: "105:04",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Ramat Aviv",
      },
    ],
    sitesActions: [
      {
        date: {
          day: "12",
          month: "04",
          year: "2024",
          time: "07:19",
        },
        location: {
          type: "Enter",
          distance: "At Site",
        },
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Yar",
        workedTime: {
          brutto: "00:00",
          netto: "00:00",
        },
        manager: "Kobi Kats",
        days: "22",
        site: "Adassa",
      },
      {
        date: {
          day: "11",
          month: "04",
          year: "2024",
          time: "10:46",
        },
        location: {
          type: "Exit",
          distance: "900m",
        },
        name: "Ion Sinu",
        photo: "https://frontwebil.github.io/RIGO-photos/img/man-yellow.svg",
        customer: "Yar",
        workedTime: {
          brutto: "10:02",
          netto: "10:26",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Adassa",
      },
      {
        date: {
          day: "08",
          month: "04",
          year: "2024",
          time: "12:20",
        },
        location: {
          type: "Brake",
          distance: "At Site",
        },
        name: "Victor Jacota",
        photo: "https://frontwebil.github.io/RIGO-photos/img/black-man.svg",
        customer: "Extra",
        workedTime: {
          brutto: "04:20",
          netto: "04:00",
        },
        manager: "Moti Rush",
        days: "16",
        site: "Adassa",
      },
      {
        date: {
          day: "06",
          month: "04",
          year: "2024",
          time: "07:52",
        },
        location: {
          type: "Colleague",
          distance: "At Site",
        },
        name: "Mihal Clmentov",
        photo: "https://frontwebil.github.io/RIGO-photos/img/woman.svg",
        customer: "Inta",
        workedTime: {
          brutto: "00:00",
          netto: "00:00",
        },
        manager: "Moti Rush",
        days: "22",
        site: "Adassa",
      },
      {
        date: {
          day: "11",
          month: "04",
          year: "2024",
          time: "18:46",
        },
        location: {
          type: "Exit",
          distance: "At Site",
        },
        name: "Anatoli Vechurko",
        photo: "https://frontwebil.github.io/RIGO-photos/img/angry-man.svg",
        customer: "Inta",
        workedTime: {
          brutto: "01:01",
          netto: "10:26",
        },
        manager: "Kobi Kats",
        days: "21",
        site: "Adassa",
      },
    ],
  }
]